package com.example.ui.strings

enum class AppLanguage(val code: String, val displayName: String) {
    GUJARATI("gu", "ગુજરાતી"),
    HINDI("hi", "हिन्दी"),
    ENGLISH("en", "English")
}

data class StringsDefinition(
    // Bottom Nav
    val navHome: String,
    val navEventBooking: String,
    val navCrew: String,
    val navSettings: String,

    // Splash
    val appSubtitle: String,

    // Home Header & Shortcuts
    val studioLocationDefault: String,
    val addCustomerBtn: String,
    val eventBookingBtn: String,
    val searchCustomerHint: String,
    val noCustomersYet: String,
    val noCustomersSub: String,

    // Customer Card
    val mobileLabel: String,
    val latestEventLabel: String,
    val dateLabel: String,
    val timeLabel: String,
    val locationLabel: String,
    val crewLabel: String,
    val noEventsBooked: String,
    val actionView: String,
    val actionEdit: String,
    val actionDelete: String,
    val actionCall: String,
    val actionWhatsApp: String,
    val actionEvents: String,

    // Add / Edit Customer
    val addCustomerTitle: String,
    val editCustomerTitle: String,
    val customerDetailsTitle: String,
    val customerNameLabel: String,
    val customerNameHint: String,
    val mobileNumberLabel: String,
    val mobileNumberHint: String,
    val noteLabel: String,
    val noteHint: String,
    val saveCustomerBtn: String,
    val saveChangesBtn: String,
    val cancelBtn: String,
    val customerSavedSuccess: String,
    val addEventBtn: String,
    val doneBtn: String,

    // Customer Details
    val customerEventsHeader: String,
    val addAnotherEventBtn: String,
    val dressCodeNoteLabel: String,
    val reminderStatusLabel: String,

    // Event Booking
    val eventBookingTitle: String,
    val customerSectionHeader: String,
    val selectCustomerHint: String,
    val addNewCustomerBtn: String,
    val eventNameLabel: String,
    val eventNameHint: String,
    val eventDateLabel: String,
    val eventTimeLabel: String,
    val eventLocationLabel: String,
    val eventLocationHint: String,
    val selectCrewBtn: String,
    val selectedCrewCount: String,
    val dressCodePlaceholder: String,
    val eventReminderHeader: String,
    val reminderToggleOn: String,
    val reminderToggleOff: String,
    val reminder1Day: String,
    val reminder12Hours: String,
    val reminder6Hours: String,
    val reminder3Hours: String,
    val reminder1Hour: String,
    val reminderCustom: String,
    val eventSummaryTitle: String,
    val saveEventBtn: String,
    val eventSavedSuccessTitle: String,

    // Event Details
    val eventDetailsTitle: String,
    val editEventTitle: String,
    val editEventBtn: String,
    val deleteEventBtn: String,
    val navigateBtn: String,
    val callCrewBtn: String,
    val markDoneBtn: String,
    val markUpcomingBtn: String,
    val statusUpcoming: String,
    val statusCompleted: String,

    // Crew
    val crewTitle: String,
    val addCrewTitle: String,
    val editCrewTitle: String,
    val addCrewBtn: String,
    val searchCrewHint: String,
    val noCrewYet: String,
    val crewNameLabel: String,
    val crewNameHint: String,
    val crewRoleLabel: String,
    val cameraEquipmentLabel: String,
    val cameraEquipmentHint: String,
    val saveCrewBtn: String,
    val crewSavedSuccess: String,
    val selectCrewModalTitle: String,
    val rolePhotographer: String,
    val roleVideographer: String,
    val roleDronePilot: String,
    val roleEditor: String,

    // Settings
    val settingsTitle: String,
    val studioProfileHeader: String,
    val studioNameLabel: String,
    val ownerNameLabel: String,
    val whatsAppNumberLabel: String,
    val fullAddressLabel: String,
    val languageHeader: String,
    val dataHeader: String,
    val backupDataBtn: String,
    val restoreDataBtn: String,
    val saveSettingsBtn: String,
    val settingsSavedToast: String,
    val lastBackupLabel: String,
    val neverBackedUp: String,

    // Confirmations & Warnings
    val deleteConfirmationTitle: String,
    val deleteCustomerConfirmMsg: String,
    val deleteEventConfirmMsg: String,
    val deleteCrewConfirmMsg: String,
    val restoreConfirmationMsg: String,
    val restoreBtn: String,
    val pastEventWarningMsg: String,
    val duplicateEventTitle: String,
    val duplicateEventMsg: String,
    val crewMobileExistsMsg: String,
    val continueBtn: String,
    val offlineIndicatorMsg: String,

    // Validations
    val errCustomerNameRequired: String,
    val errValidMobileRequired: String,
    val errCustomerRequired: String,
    val errEventNameRequired: String,
    val errEventDateRequired: String,
    val errEventTimeRequired: String,
    val errEventLocationRequired: String,
    val errAtLeastOneCrewRequired: String,
    val errReminderBeforeEvent: String,
    val errReminderPast: String,
    val errSaveFailed: String,
    val retryBtn: String
)

object AppStrings {
    val Gujarati = StringsDefinition(
        navHome = "હોમ",
        navEventBooking = "ઇવેન્ટ બુકિંગ",
        navCrew = "ક્રૂ (ટીમ)",
        navSettings = "સેટિંગ્સ",
        appSubtitle = "ફોટો • વિડિયો • ઇવેન્ટ્સ",
        studioLocationDefault = "India",
        addCustomerBtn = "+ નવો ગ્રાહક ઉમેરો",
        eventBookingBtn = "+ ઇવેન્ટ બુકિંગ",
        searchCustomerHint = "ગ્રાહકનું નામ અથવા મોબાઈલ શોધો...",
        noCustomersYet = "હજી કોઈ ગ્રાહક નથી",
        noCustomersSub = "પ્રથમ ગ્રાહક ઉમેરીને શરૂઆત કરો",
        mobileLabel = "મોબાઈલ",
        latestEventLabel = "છેલ્લી ઇવેન્ટ",
        dateLabel = "તારીખ",
        timeLabel = "સમય",
        locationLabel = "સ્થળ",
        crewLabel = "ક્રૂ ટીમ",
        noEventsBooked = "હજી કોઈ ઇવેન્ટ બુક નથી",
        actionView = "જુઓ",
        actionEdit = "સુધારો",
        actionDelete = "કાઢી નાખો",
        actionCall = "કોલ",
        actionWhatsApp = "વ્હોટ્સએપ",
        actionEvents = "ઇવેન્ટ્સ",
        addCustomerTitle = "ગ્રાહક ઉમેરો",
        editCustomerTitle = "ગ્રાહક સુધારો",
        customerDetailsTitle = "ગ્રાહકની વિગત",
        customerNameLabel = "ગ્રાહકનું નામ *",
        customerNameHint = "ગ્રાહકનું નામ લખો",
        mobileNumberLabel = "મોબાઈલ નંબર *",
        mobileNumberHint = "મોબાઈલ નંબર દાખલ કરો",
        noteLabel = "નોંધ (વૈકલ્પિક)",
        noteHint = "વિશેષ નોંધ લખો...",
        saveCustomerBtn = "ગ્રાહક સેવ કરો",
        saveChangesBtn = "ફેરફારો સેવ કરો",
        cancelBtn = "રદ કરો",
        customerSavedSuccess = "ગ્રાહક સફળતાપૂર્વક સેવ થઈ ગયો.",
        addEventBtn = "📅 ઇવેન્ટ ઉમેરો",
        doneBtn = "પૂર્ણ (Done)",
        customerEventsHeader = "ઇવેન્ટ્સ",
        addAnotherEventBtn = "+ અન્ય ઇવેન્ટ ઉમેરો",
        dressCodeNoteLabel = "ડ્રેસ કોડ / ખાસ નોંધ",
        reminderStatusLabel = "રીમાઇન્ડર",
        eventBookingTitle = "ઇવેન્ટ બુકિંગ",
        customerSectionHeader = "ગ્રાહકની પસંદગી",
        selectCustomerHint = "હાલના ગ્રાહક પસંદ કરો",
        addNewCustomerBtn = "+ નવો ગ્રાહક ઉમેરો",
        eventNameLabel = "ઇવેન્ટનું નામ *",
        eventNameHint = "લગ્ન / હલ્દી / રીસેપ્શન / જન્મદિવસ",
        eventDateLabel = "ઇવેન્ટ તારીખ *",
        eventTimeLabel = "ઇવેન્ટ સમય *",
        eventLocationLabel = "ઇવેન્ટ સ્થળ *",
        eventLocationHint = "ઇવેન્ટનું સ્થળ / હોલ લખો",
        selectCrewBtn = "ક્રૂ પસંદ કરો",
        selectedCrewCount = "પસંદ કરેલ સભ્યો",
        dressCodePlaceholder = "ડ્રેસ કોડ / સ્પેશિયલ નોટ લખો...",
        eventReminderHeader = "🔔 ઇવેન્ટ રીમાઇન્ડર",
        reminderToggleOn = "રીમાઇન્ડર ચાલુ (ON)",
        reminderToggleOff = "રીમાઇન્ડર બંધ (OFF)",
        reminder1Day = "૧ દિવસ પહેલા",
        reminder12Hours = "૧૨ કલાક પહેલા",
        reminder6Hours = "૬ કલાક પહેલા",
        reminder3Hours = "૩ કલાક પહેલા",
        reminder1Hour = "૧ કલાક પહેલા",
        reminderCustom = "કસ્ટમ સમય",
        eventSummaryTitle = "ઇવેન્ટ સારાંશ",
        saveEventBtn = "💾 ઇવેન્ટ સેવ કરો",
        eventSavedSuccessTitle = "ઇવેન્ટ સફળતાપૂર્વક સેવ થઈ ગઈ",
        eventDetailsTitle = "ઇવેન્ટ વિગત",
        editEventTitle = "ઇવેન્ટ સુધારો",
        editEventBtn = "✏️ ઇવેન્ટ સુધારો",
        deleteEventBtn = "🗑️ ઇવેન્ટ રદ કરો",
        navigateBtn = "📍 લોકેશન નેવિગેટ",
        callCrewBtn = "📞 ક્રૂને કોલ કરો",
        markDoneBtn = "✔ પૂર્ણ માર્ક કરો",
        markUpcomingBtn = "ઇવેન્ટ આગામી કરો",
        statusUpcoming = "આગામી (Upcoming)",
        statusCompleted = "પૂર્ણ (Done)",
        crewTitle = "ક્રૂ ટીમ",
        addCrewTitle = "નવો ક્રૂ ઉમેરો",
        editCrewTitle = "ક્રૂ સુધારો",
        addCrewBtn = "+ નવો ક્રૂ ઉમેરો",
        searchCrewHint = "ક્રૂનું નામ, મોબાઈલ કે રોલ શોધો...",
        noCrewYet = "હજી કોઈ ક્રૂ મેમ્બર નથી",
        crewNameLabel = "ક્રૂ સભ્યનું નામ *",
        crewNameHint = "નામ દાખલ કરો",
        crewRoleLabel = "રોલ / કામગીરી *",
        cameraEquipmentLabel = "કેમેરા / સાધનોની વિગત",
        cameraEquipmentHint = "દા.ત. Sony FX3, DJI Mini 4 Pro",
        saveCrewBtn = "ક્રૂ સેવ કરો",
        crewSavedSuccess = "ક્રૂ સફળતાપૂર્વક સેવ થઈ ગયો.",
        selectCrewModalTitle = "ક્રૂ ટીમ પસંદ કરો",
        rolePhotographer = "ફોટોગ્રાફર",
        roleVideographer = "વિડિયોગ્રાફર",
        roleDronePilot = "ડ્રોન પાયલટ",
        roleEditor = "એડિટર",
        settingsTitle = "સેટિંગ્સ",
        studioProfileHeader = "સ્ટુડિયો પ્રોફાઈલ",
        studioNameLabel = "સ્ટુડિયોનું નામ",
        ownerNameLabel = "માલિકનું નામ",
        whatsAppNumberLabel = "વ્હોટ્સએપ નંબર",
        fullAddressLabel = "પૂરું સરનામું",
        languageHeader = "ભાષા (Language)",
        dataHeader = "ડેટા બેકઅપ / રિસ્ટોર",
        backupDataBtn = "ડેટા બેકઅપ લો",
        restoreDataBtn = "ડેટા રિસ્ટોર કરો",
        saveSettingsBtn = "સેટિંગ્સ સેવ કરો",
        settingsSavedToast = "સેટિંગ્સ સેવ થઈ ગયા છે.",
        lastBackupLabel = "છેલ્લું બેકઅપ:",
        neverBackedUp = "ક્યારેય નથી લીધું",
        deleteConfirmationTitle = "કાઢી નાખવાની પુષ્ટિ",
        deleteCustomerConfirmMsg = "શું તમે ખરેખર આ ગ્રાહકને કાઢી નાખવા માંગો છો? તેમના ઇવેન્ટ્સ પણ હટશે.",
        deleteEventConfirmMsg = "Are you sure you want to delete this event? શું તમે આ ઇવેન્ટ રદ કરવા માંગો છો?",
        deleteCrewConfirmMsg = "શું તમે આ ક્રૂ સભ્યને હટાવવા માંગો છો?",
        restoreConfirmationMsg = "Restoring data may replace current app data. Continue? ડેટા રિસ્ટોર કરવાથી વર્તમાન ડેટા બદલાઈ શકે છે.",
        restoreBtn = "રિસ્ટોર કરો",
        pastEventWarningMsg = "આ Eventની તારીખ પસાર થઈ ગઈ છે. શું તમે ચાલુ રાખવા માંગો છો?",
        duplicateEventTitle = "Similar Event Already Exists",
        duplicateEventMsg = "આ Customer માટે આ જ તારીખ અને સમયે Event પહેલેથી છે. શું તમે ફરીથી Event બનાવવું છે?",
        crewMobileExistsMsg = "આ મોબાઈલ નંબર પહેલેથી રજીસ્ટર થયેલો છે.",
        continueBtn = "ચાલુ રાખો (Continue)",
        offlineIndicatorMsg = "Data saved on this device. Internet મળતાં sync થશે.",
        errCustomerNameRequired = "Customer name is required. ગ્રાહકનું નામ જરૂરી છે.",
        errValidMobileRequired = "Please enter a valid mobile number. સાચો ૧૦ અંકનો મોબાઈલ દાખલ કરો.",
        errCustomerRequired = "Customer પસંદ કરો.",
        errEventNameRequired = "Event Name is required.",
        errEventDateRequired = "Event Date is required.",
        errEventTimeRequired = "Event Time is required.",
        errEventLocationRequired = "Event Location is required.",
        errAtLeastOneCrewRequired = "At least one Crew member is required.",
        errReminderBeforeEvent = "Reminder time must be before the event time.",
        errReminderPast = "રીમાઇન્ડર ભૂતકાળના સમયમાં ન હોઈ શકે.",
        errSaveFailed = "Data save થઈ શક્યું નથી. કૃપા કરીને ફરી પ્રયાસ કરો.",
        retryBtn = "ફરી પ્રયાસ કરો (Retry)"
    )

    val Hindi = StringsDefinition(
        navHome = "होम",
        navEventBooking = "इवेंट बुकिंग",
        navCrew = "क्रू (टीम)",
        navSettings = "सेटिंग्स",
        appSubtitle = "फोटो • वीडियो • इवेंट्स",
        studioLocationDefault = "India",
        addCustomerBtn = "+ नया ग्राहक जोड़ें",
        eventBookingBtn = "+ इवेंट बुकिंग",
        searchCustomerHint = "ग्राहक का नाम या मोबाइल खोजें...",
        noCustomersYet = "अभी कोई ग्राहक नहीं है",
        noCustomersSub = "पहला ग्राहक जोड़कर शुरुआत करें",
        mobileLabel = "मोबाइल",
        latestEventLabel = "नवीनतम इवेंट",
        dateLabel = "तारीख",
        timeLabel = "समय",
        locationLabel = "स्थान",
        crewLabel = "क्रू टीम",
        noEventsBooked = "कोई इवेंट बुक नहीं है",
        actionView = "देखें",
        actionEdit = "बदलें",
        actionDelete = "हटाएं",
        actionCall = "कॉल",
        actionWhatsApp = "व्हाट्सएप",
        actionEvents = "इवेंट्स",
        addCustomerTitle = "ग्राहक जोड़ें",
        editCustomerTitle = "ग्राहक संपादित करें",
        customerDetailsTitle = "ग्राहक विवरण",
        customerNameLabel = "ग्राहक का नाम *",
        customerNameHint = "ग्राहक का नाम दर्ज करें",
        mobileNumberLabel = "मोबाइल नंबर *",
        mobileNumberHint = "10 अंकों का मोबाइल नंबर",
        noteLabel = "नोट (वैकल्पिक)",
        noteHint = "कोई विशेष विवरण जोड़ें...",
        saveCustomerBtn = "ग्राहक सहेजें",
        saveChangesBtn = "परिवर्तन सहेजें",
        cancelBtn = "रद्द करें",
        customerSavedSuccess = "ग्राहक सफलतापूर्वक सहेजा गया।",
        addEventBtn = "📅 इवेंट जोड़ें",
        doneBtn = "पूर्ण (Done)",
        customerEventsHeader = "इवेंट्स",
        addAnotherEventBtn = "+ अन्य इवेंट जोड़ें",
        dressCodeNoteLabel = "ड्रेस कोड / विशेष नोट",
        reminderStatusLabel = "रिमाइंडर",
        eventBookingTitle = "इवेंट बुकिंग",
        customerSectionHeader = "ग्राहक चुनें",
        selectCustomerHint = "मौजूदा ग्राहक चुनें",
        addNewCustomerBtn = "+ नया ग्राहक जोड़ें",
        eventNameLabel = "इवेंट का नाम *",
        eventNameHint = "शादी / हल्दी / रिसेप्शन / जन्मदिन",
        eventDateLabel = "इवेंट तारीख *",
        eventTimeLabel = "इवेंट समय *",
        eventLocationLabel = "इवेंट स्थान *",
        eventLocationHint = "इवेंट स्थल / हॉल दर्ज करें",
        selectCrewBtn = "क्रू चुनें",
        selectedCrewCount = "चयनित सदस्य",
        dressCodePlaceholder = "ड्रेस कोड / विशेष निर्देश लिखें...",
        eventReminderHeader = "🔔 इवेंट रिमाइंडर",
        reminderToggleOn = "रिमाइंडर चालू (ON)",
        reminderToggleOff = "रिमाइंडर बंद (OFF)",
        reminder1Day = "1 दिन पहले",
        reminder12Hours = "12 घंटे पहले",
        reminder6Hours = "6 घंटे पहले",
        reminder3Hours = "3 घंटे पहले",
        reminder1Hour = "1 घंटा पहले",
        reminderCustom = "कस्टम समय",
        eventSummaryTitle = "इवेंट सारांश",
        saveEventBtn = "💾 इवेंट सहेजें",
        eventSavedSuccessTitle = "इवेंट सफलतापूर्वक सहेजा गया",
        eventDetailsTitle = "इवेंट विवरण",
        editEventTitle = "इवेंट संपादित करें",
        editEventBtn = "✏️ इवेंट संपादित करें",
        deleteEventBtn = "🗑️ इवेंट हटाएं",
        navigateBtn = "📍 मैप में देखें",
        callCrewBtn = "📞 क्रू को कॉल करें",
        markDoneBtn = "✔ पूर्ण मार्क करें",
        markUpcomingBtn = "आगामी मार्क करें",
        statusUpcoming = "आगामी (Upcoming)",
        statusCompleted = "पूर्ण (Completed)",
        crewTitle = "क्रू टीम",
        addCrewTitle = "नया क्रू जोड़ें",
        editCrewTitle = "क्रू संपादित करें",
        addCrewBtn = "+ नया क्रू जोड़ें",
        searchCrewHint = "क्रू का नाम, मोबाइल या रोल खोजें...",
        noCrewYet = "कोई क्रू सदस्य नहीं मिला",
        crewNameLabel = "क्रू सदस्य का नाम *",
        crewNameHint = "नाम दर्ज करें",
        crewRoleLabel = "रोल / भूमिका *",
        cameraEquipmentLabel = "कैमरा / उपकरण विवरण",
        cameraEquipmentHint = "जैसे Sony A7IV, DJI Gimbal",
        saveCrewBtn = "क्रू सहेजें",
        crewSavedSuccess = "क्रू सदस्य सफलतापूर्वक सहेजा गया।",
        selectCrewModalTitle = "क्रू टीम चुनें",
        rolePhotographer = "फोटोग्राफर",
        roleVideographer = "वीडियोग्राफर",
        roleDronePilot = "ड्रोन पायलट",
        roleEditor = "एडिटर",
        settingsTitle = "सेटिंग्स",
        studioProfileHeader = "स्टूडियो प्रोफ़ाइल",
        studioNameLabel = "स्टूडियो का नाम",
        ownerNameLabel = "मालिक का नाम",
        whatsAppNumberLabel = "व्हाट्सएप नंबर",
        fullAddressLabel = "पूरा पता",
        languageHeader = "भाषा (Language)",
        dataHeader = "डेटा बैकअप / रीस्टोर",
        backupDataBtn = "डेटा बैकअप लें",
        restoreDataBtn = "डेटा रीस्टोर करें",
        saveSettingsBtn = "सेटिंग्स सहेजें",
        settingsSavedToast = "सेटिंग्स सफलतापूर्वक सहेजी गईं।",
        lastBackupLabel = "अंतिम बैकअप:",
        neverBackedUp = "कभी नहीं",
        deleteConfirmationTitle = "हटाने की पुष्टि",
        deleteCustomerConfirmMsg = "क्या आप वाकई इस ग्राहक को हटाना चाहते हैं? उनकी सभी इवेंट्स भी हट जाएंगी।",
        deleteEventConfirmMsg = "Are you sure you want to delete this event?",
        deleteCrewConfirmMsg = "क्या आप इस क्रू सदस्य को हटाना चाहते हैं?",
        restoreConfirmationMsg = "Restoring data may replace current app data. Continue?",
        restoreBtn = "रीस्टोर करें",
        pastEventWarningMsg = "इस इवेंट की तारीख बीत चुकी है। क्या आप जारी रखना चाहते हैं?",
        duplicateEventTitle = "Similar Event Already Exists",
        duplicateEventMsg = "इस ग्राहक के लिए इस तारीख और समय पर पहले से इवेंट है। क्या आप फिर भी बनाना चाहते हैं?",
        crewMobileExistsMsg = "यह मोबाइल नंबर पहले से दर्ज है।",
        continueBtn = "जारी रखें (Continue)",
        offlineIndicatorMsg = "ડેટા આ ફોન પર સેવ છે. ઇન્ટરનેટ મળશે ત્યારે સિન્ક થશે.",
        errCustomerNameRequired = "Customer name is required. ग्राहक का नाम आवश्यक है।",
        errValidMobileRequired = "Please enter a valid mobile number. सही मोबाइल नंबर दर्ज करें।",
        errCustomerRequired = "Customer પસંદ કરો (ग्राहक चुनें)।",
        errEventNameRequired = "Event Name is required.",
        errEventDateRequired = "Event Date is required.",
        errEventTimeRequired = "Event Time is required.",
        errEventLocationRequired = "Event Location is required.",
        errAtLeastOneCrewRequired = "At least one Crew member is required.",
        errReminderBeforeEvent = "Reminder time must be before the event time.",
        errReminderPast = "रिमाइंडर समय पहले का नहीं हो सकता।",
        errSaveFailed = "डेटा सहेजने में विफल। कृपया पुन: प्रयास करें।",
        retryBtn = "पुन: प्रयास करें (Retry)"
    )

    val English = StringsDefinition(
        navHome = "Home",
        navEventBooking = "Event Booking",
        navCrew = "Crew",
        navSettings = "Settings",
        appSubtitle = "Photo • Video • Events",
        studioLocationDefault = "India",
        addCustomerBtn = "+ Add Customer",
        eventBookingBtn = "+ Event Booking",
        searchCustomerHint = "Search Customer by Name or Mobile",
        noCustomersYet = "No customers yet",
        noCustomersSub = "Start by adding your first customer",
        mobileLabel = "Mobile",
        latestEventLabel = "Latest Event",
        dateLabel = "Date",
        timeLabel = "Time",
        locationLabel = "Location",
        crewLabel = "Crew",
        noEventsBooked = "No events booked yet",
        actionView = "View",
        actionEdit = "Edit",
        actionDelete = "Delete",
        actionCall = "Call",
        actionWhatsApp = "WhatsApp",
        actionEvents = "Events",
        addCustomerTitle = "Add Customer",
        editCustomerTitle = "Edit Customer",
        customerDetailsTitle = "Customer Details",
        customerNameLabel = "Customer Name *",
        customerNameHint = "Enter customer name",
        mobileNumberLabel = "Mobile Number *",
        mobileNumberHint = "Enter mobile number",
        noteLabel = "Note (Optional)",
        noteHint = "Add a note...",
        saveCustomerBtn = "Save Customer",
        saveChangesBtn = "Save Changes",
        cancelBtn = "Cancel",
        customerSavedSuccess = "Customer successfully saved.",
        addEventBtn = "📅 Add Event",
        doneBtn = "Done",
        customerEventsHeader = "Events",
        addAnotherEventBtn = "+ Add Another Event",
        dressCodeNoteLabel = "Dress Code / Special Note",
        reminderStatusLabel = "Reminder",
        eventBookingTitle = "Event Booking",
        customerSectionHeader = "Customer",
        selectCustomerHint = "Select Existing Customer",
        addNewCustomerBtn = "+ Add New Customer",
        eventNameLabel = "Event Name *",
        eventNameHint = "Wedding / Haldi / Reception / Birthday",
        eventDateLabel = "Event Date *",
        eventTimeLabel = "Event Time *",
        eventLocationLabel = "Event Location *",
        eventLocationHint = "Enter event location",
        selectCrewBtn = "Select Crew",
        selectedCrewCount = "members selected",
        dressCodePlaceholder = "Dress Code / Special Note લખો...",
        eventReminderHeader = "🔔 Event Reminder",
        reminderToggleOn = "Reminder ON",
        reminderToggleOff = "Reminder OFF",
        reminder1Day = "1 Day Before",
        reminder12Hours = "12 Hours Before",
        reminder6Hours = "6 Hours Before",
        reminder3Hours = "3 Hours Before",
        reminder1Hour = "1 Hour Before",
        reminderCustom = "Custom",
        eventSummaryTitle = "Event Summary",
        saveEventBtn = "💾 Save Event",
        eventSavedSuccessTitle = "Event Saved Successfully",
        eventDetailsTitle = "Event Details",
        editEventTitle = "Edit Event",
        editEventBtn = "✏ Edit Event",
        deleteEventBtn = "🗑 Delete Event",
        navigateBtn = "📍 Navigate",
        callCrewBtn = "📞 Call Crew",
        markDoneBtn = "✔ Mark Done",
        markUpcomingBtn = "Mark Upcoming",
        statusUpcoming = "Upcoming",
        statusCompleted = "Completed",
        crewTitle = "Crew",
        addCrewTitle = "Add Crew",
        editCrewTitle = "Edit Crew",
        addCrewBtn = "+ Add Crew",
        searchCrewHint = "Search Crew",
        noCrewYet = "No crew members yet",
        crewNameLabel = "Crew Name *",
        crewNameHint = "Enter crew name",
        crewRoleLabel = "Role *",
        cameraEquipmentLabel = "Camera / Equipment Details",
        cameraEquipmentHint = "e.g. Sony A7M4, 24-70mm lens",
        saveCrewBtn = "Save Crew",
        crewSavedSuccess = "Crew successfully saved.",
        selectCrewModalTitle = "Select Crew Members",
        rolePhotographer = "Photographer",
        roleVideographer = "Videographer",
        roleDronePilot = "Drone Pilot",
        roleEditor = "Editor",
        settingsTitle = "Settings",
        studioProfileHeader = "Studio Profile",
        studioNameLabel = "Studio Name",
        ownerNameLabel = "Owner Name",
        whatsAppNumberLabel = "WhatsApp Number",
        fullAddressLabel = "Full Address",
        languageHeader = "Language",
        dataHeader = "Data",
        backupDataBtn = "Backup Data",
        restoreDataBtn = "Restore Data",
        saveSettingsBtn = "Save Settings",
        settingsSavedToast = "Settings saved successfully",
        lastBackupLabel = "Last backup:",
        neverBackedUp = "Never",
        deleteConfirmationTitle = "Delete Confirmation",
        deleteCustomerConfirmMsg = "Are you sure you want to delete this customer? All events will also be deleted.",
        deleteEventConfirmMsg = "Are you sure you want to delete this event?",
        deleteCrewConfirmMsg = "Are you sure you want to delete this crew member?",
        restoreConfirmationMsg = "Restoring data may replace current app data. Continue?",
        restoreBtn = "Restore",
        pastEventWarningMsg = "આ Eventની તારીખ પસાર થઈ ગઈ છે. શું તમે ચાલુ રાખવા માંગો છો?",
        duplicateEventTitle = "Similar Event Already Exists",
        duplicateEventMsg = "આ Customer માટે આ જ તારીખ અને સમયે Event પહેલેથી છે. શું તમે ફરીથી Event બનાવવું છે?",
        crewMobileExistsMsg = "This mobile number is already registered.",
        continueBtn = "Continue",
        offlineIndicatorMsg = "Data saved on this device. Internet મળતાં sync થશે.",
        errCustomerNameRequired = "Customer name is required.",
        errValidMobileRequired = "Please enter a valid mobile number.",
        errCustomerRequired = "Customer પસંદ કરો.",
        errEventNameRequired = "Event Name is required.",
        errEventDateRequired = "Event Date is required.",
        errEventTimeRequired = "Event Time is required.",
        errEventLocationRequired = "Event Location is required.",
        errAtLeastOneCrewRequired = "At least one Crew member is required.",
        errReminderBeforeEvent = "Reminder time must be before the event time.",
        errReminderPast = "Reminder time cannot be in the past.",
        errSaveFailed = "Data save થઈ શક્યું નથી. કૃપા કરીને ફરી પ્રયાસ કરો.",
        retryBtn = "Retry"
    )

    fun get(language: AppLanguage): StringsDefinition {
        return when (language) {
            AppLanguage.GUJARATI -> Gujarati
            AppLanguage.HINDI -> Hindi
            AppLanguage.ENGLISH -> English
        }
    }
}
